// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUtvmNkUdghvYqIaN-50nD7u9EsaH4uYA',
    appId: '1:984365561712:web:2e35086cba27adc0d001b5',
    messagingSenderId: '984365561712',
    projectId: 'lmsupportagent',
    authDomain: 'lmsupportagent.firebaseapp.com',
    storageBucket: 'lmsupportagent.firebasestorage.app',
    measurementId: 'G-1HM8RYPPTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsy37RDwcyyEqdlxYqz77vQMhYwtJzrI',
    appId: '1:984365561712:android:a2fe6a4bb8bed851d001b5',
    messagingSenderId: '984365561712',
    projectId: 'lmsupportagent',
    storageBucket: 'lmsupportagent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEQB2AWil1T0s0TXXuVl03YK3rQGhy5Uc',
    appId: '1:984365561712:ios:1c8c69c197c3228bd001b5',
    messagingSenderId: '984365561712',
    projectId: 'lmsupportagent',
    storageBucket: 'lmsupportagent.firebasestorage.app',
    iosBundleId: 'com.example.lmrepaircrmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEQB2AWil1T0s0TXXuVl03YK3rQGhy5Uc',
    appId: '1:984365561712:ios:1c8c69c197c3228bd001b5',
    messagingSenderId: '984365561712',
    projectId: 'lmsupportagent',
    storageBucket: 'lmsupportagent.firebasestorage.app',
    iosBundleId: 'com.example.lmrepaircrmapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUtvmNkUdghvYqIaN-50nD7u9EsaH4uYA',
    appId: '1:984365561712:web:d75e005eedbe800bd001b5',
    messagingSenderId: '984365561712',
    projectId: 'lmsupportagent',
    authDomain: 'lmsupportagent.firebaseapp.com',
    storageBucket: 'lmsupportagent.firebasestorage.app',
    measurementId: 'G-WM4HEX8ZV9',
  );
}
